=== Jakmaster199/PristonTale-XML-Lib/schemas/items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Start of Given Stats -->
    <xs:simpleType name="givenStatsType">
        <xs:restriction base="xs:token">
            <!-- Weapons -->
            <xs:enumeration value="attack_damage" />
            <xs:enumeration value="attack_speed" />
            <xs:enumeration value="critical_rate" />
            <xs:enumeration value="attack_range" />
            <xs:enumeration value="attack_rating" />

            <!-- Boots -->
            <xs:enumeration value="movement_speed" />

            <!-- Armor, Rober & Shields -->
            <xs:enumeration value="absorption" />
            <xs:enumeration value="block_rating" />
            <xs:enumeration value="defense" />

            <!-- Bracelets -->
            <xs:enumeration value="potion_space" />

            <!-- Rings & Necklage -->
            <xs:enumeration value="mana_recovery" />
            <xs:enumeration value="stamina_recovery" />
            <xs:enumeration value="health_recovery" />

            <!-- Rings & Necklage  (?)-->
            <xs:enumeration value="spec_mana_recovery" />
            <xs:enumeration value="spec_stamina_recovery" />
            <xs:enumeration value="spec_health_recovery" />

            <!-- Various -->
            <xs:enumeration value="max_health" />
            <xs:enumeration value="max_mana" />
            <xs:enumeration value="max_stamina" />

            <!-- Resistances -->
            <xs:enumeration value="bionic_resistance" />
            <xs:enumeration value="wind_resistance" />
            <xs:enumeration value="water_resistance" />
            <xs:enumeration value="fire_resistance" />
            <xs:enumeration value="ice_resistance" />
            <xs:enumeration value="lighting_resistance" />
            <xs:enumeration value="poison_resistance" />
            <xs:enumeration value="earth_resistance" />

        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="setStatType">
        <xs:attribute name="stat" type="givenStatsType" use="required" />
        <xs:attribute name="value" type="xs:token" use="required" />
    </xs:complexType>

    <xs:complexType name="setStatsType" mixed="true">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="set" type="setStatType" /> <!-- Force value -->
            <xs:element name="add" type="setStatType" /> <!-- Add to current value -->
            <xs:element name="sub" type="setStatType" /> <!-- Substract from current value -->
        </xs:choice>
    </xs:complexType>
    <!-- End of Given Stats -->

    <!-- Start of Global Set Types -->
    <xs:complexType name="setGlobalType">
        <xs:attribute name="name" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <!-- All Items -->
                    <xs:enumeration value="armor_type" />
                    <xs:enumeration value="weapon_type" />

                    <xs:enumeration value="default_action" />
                    <xs:enumeration value="body_part" />
                    <xs:enumeration value="image" />

                    <xs:enumeration value="price" />
                    <xs:enumeration value="weight" />
                    <xs:enumeration value="durability" />

                    <!-- Unique Items -->
                    <xs:enumeration value="unique_item" />
                    <xs:enumeration value="max_ocurrency" />

                    <!-- Premium Items -->
                    <xs:enumeration value="premium_item" />
                    <xs:enumeration value="duration" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="value" type="xs:token" use="required" />
    </xs:complexType>
    <!-- End of Global Set Types -->

    <!-- Start of Required Stats-->
    <xs:simpleType name="StatsType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="level" />

            <xs:enumeration value="strength" />
            <xs:enumeration value="spirit" />
            <xs:enumeration value="talent" />
            <xs:enumeration value="agility" />
            <xs:enumeration value="vitality" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="baseStatType">
        <xs:attribute name="stat" type="StatsType" use="required" />
        <xs:attribute name="value" type="xs:decimal" use="required" />
    </xs:complexType>

    <xs:complexType name="reqStatsType" mixed="true">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="base" type="baseStatType" />
        </xs:choice>
    </xs:complexType>
    <!-- End of Required Stats-->

    <xs:complexType name="itemType">

        <xs:sequence maxOccurs="1" minOccurs="1">
            <xs:element name="set" maxOccurs="unbounded" minOccurs="1" type="setGlobalType"  /> <!-- Core Stats -->
            <xs:element name="stats" maxOccurs="1" minOccurs="1" type="setStatsType" /> <!-- Assigned Stats -->
            <xs:element name="req" maxOccurs="1" minOccurs="1" type="reqStatsType" /> <!-- Required Stats -->
            <!-- xs:element name="cond" maxOccurs="1" minOccurs="0" type="xs:string" /--> <!-- Conditionals for equip/usage -->
        </xs:sequence>

        <xs:attribute name="id" type="xs:normalizedString" use="required" />
        <xs:attribute name="name" type="xs:normalizedString" use="required" />
        <xs:attribute name="type" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="Defense" /> <!-- Armor, Robe, Shield, Cosmetic Armor (?) -->
                    <xs:enumeration value="Accesory" /> <!-- Bracelet, Ring, Necklage, Sheltom, Earrings -->
                    <xs:enumeration value="Weapon" /> <!-- Javelin, Mace, Sword, Wand, Staff, Big Sword, Dagger, Bow, HandBow -->
                    <xs:enumeration value="QuestItem" /> <!-- Quest Items -->
                    <xs:enumeration value="EtcItem" /> <!-- Crystals, Potions, Aging Items, Scrolls, Hair dyes, Premium Items -->
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="item" type="itemType" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Jakmaster199/PristonTale-XML-Lib/examples/Swords.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../../schemas/items.xsd">
    <item id="WS210" type="Weapon" name="Platinum Sword">
        <set name="weapon_type" value="Sword" />
        <set name="body_part" value="lhand" />
        <set name="default_action" value="EQUIP" />
        <set name="image" value="sinimages\items\weapons\Sword\itWS210.bmp" />
        <set name="weight" value="13" />
        <set name="price" value="30000" />
        <set name="durability" value="100;100" />
        <stats>
            <add stat="attack_damage" value="17;17;22;22" />
            <add stat="attack_speed" value="8" />
            <add stat="attack_rating" value="100;100" />
            <add stat="critical_rate" value="12" />
            <add stat="block_rating" value="7;7" />
        </stats>
        <req>
            <base stat="level" value="40" />
        </req>
    </item>
    <item id="WS223" type="Weapon" name="Immortal sword">
        <set name="weapon_type" value="Sword" />
        <set name="body_part" value="lhand" />
        <set name="default_action" value="EQUIP" />
        <set name="image" value="sinimages\items\weapons\Sword\itWS223.bmp" />
        <set name="weight" value="50" />
        <set name="price" value="1800000" />
        <set name="durability" value="70;70" />
        <stats>
            <add stat="attack_damage" value="71;71;86;86" />
            <add stat="attack_speed" value="8" />
            <add stat="attack_rating" value="285;285" />
            <add stat="critical_rate" value="24" />
            <add stat="block_rating" value="10;10" />
        </stats>
        <req>
            <base stat="level" value="100" />
        </req>
    </item>
    <item id="WS201" type="Weapon" name="Dagger">
        <set name="weapon_type" value="Sword" />
        <set name="body_part" value="lhand" />
        <set name="default_action" value="EQUIP" />
        <set name="image" value="sinimages\items\weapons\Sword\itWS201.bmp" />
        <set name="weight" value="2" />
        <set name="price" value="60" />
        <set name="durability" value="15;25" />
        <stats>
            <add stat="attack_damage" value="1;2;3;3" />
            <add stat="attack_speed" value="7" />
            <add stat="attack_rating" value="50;56" />
            <add stat="critical_rate" value="1" />
        </stats>
        <req>
        </req>
    </item>
    <item id="WS202" type="Weapon" name="Celtic Dagger">
        <set name="weapon_type" value="Sword" />
        <set name="body_part" value="lhand" />
        <set name="default_action" value="EQUIP" />
        <set name="image" value="sinimages\items\weapons\Sword\itWS202.bmp" />
        <set name="weight" value="3" />
        <set name="price" value="250" />
        <set name="durability" value="18;31" />
        <stats>
            <add stat="attack_damage" value="2;2;4;5" />
            <add stat="attack_speed" value="7" />
            <add stat="attack_rating" value="55;62" />
            <add stat="critical_rate" value="1" />
        </stats>
        <req>
        </req>
    </item>
    <item id="WS203" type="Weapon" name="Sword Breaker">
        <set name="weapon_type" value="Sword" />
        <set name="body_part" value="lhand" />
        <set name="default_action" value="EQUIP" />
        <set name="image" value="sinimages\items\weapons\Sword\itWS203.bmp" />
        <set name="weight" value="4" />
        <set name="price" value="560" />
        <set name="durability" value="30;35" />
        <stats>
            <add stat="attack_damage" value="2;3;6;7" />
            <add stat="attack_speed" value="7" />
            <add stat="attack_rating" value="45;52" />
            <add stat="critical_rate" value="2" />
        </stats>
        <req>
            <base stat="strength" value="30" />
        </req>
    </item>
    <item id="WS204" type="Weapon" name="Short Sword">
        <set name="weapon_type" value="Sword" />
        <set name="body_part" value="lhand" />
        <set name="default_action" value="EQUIP" />
        <set name="image" value="sinimages\items\weapons\Sword\itWS204.bmp" />
        <set name="weight" value="5" />
        <set name="price" value="1300" />
        <set name="durability" value="40;48" />
        <stats>
            <add stat="attack_damage" value="3;4;5;8" />
            <add stat="attack_speed" value="8" />
            <add stat="attack_rating" value="38;44" />
            <add stat="critical_rate" value="3" />
        </stats>
        <req>
            <base stat="level" value="6" />
            <base stat="strength" value="36" />
        </req>
    </item>
    <item id="WS205" type="Weapon" name="Long Sword">
        <set name="weapon_type" value="Sword" />
        <set name="body_part" value="lhand" />
        <set name="default_action" value="EQUIP" />
        <set name="image" value="sinimages\items\weapons\Sword\itWS205.bmp" />
        <set name="weight" value="6" />
        <set name="price" value="2600" />
        <set name="durability" value="48;55" />
        <stats>
            <add stat="attack_damage" value="7;8;11;13" />
            <add stat="attack_speed" value="7" />
            <add stat="attack_rating" value="40;45" />
            <add stat="critical_rate" value="7;" />
            <add stat="block_rating" value="4;4" />
        </stats>
        <req>
            <base stat="level" value="9" />
            <base stat="strength" value="40" />
            <base stat="talent" value="30" />
        </req>
    </item>
    <item id="WS206" type="Weapon" name="Broad Sword">
        <set name="weapon_type" value="Sword" />
        <set name="body_part" value="lhand" />
        <set name="default_action" value="EQUIP" />
        <set name="image" value="sinimages\items\weapons\Sword\itWS206.bmp" />
        <set name="weight" value="9" />
        <set name="price" value="3500" />
        <set name="durability" value="52;63" />
        <stats>
            <add stat="attack_damage" value="5;8;10;12" />
            <add stat="attack_speed" value="6" />
            <add stat="attack_rating" value="45;53" />
            <add stat="critical_rate" value="5;" />
        </stats>
        <req>
            <base stat="level" value="13" />
            <base stat="strength" value="50" />
            <base stat="talent" value="36" />
        </req>
    </item>
    <item id="WS207" type="Weapon" name="Blade">
        <set name="weapon_type" value="Sword" />
        <set name="body_part" value="lhand" />
        <set name="default_action" value="EQUIP" />
        <set name="image" value="sinimages\items\weapons\Sword\itWS207.bmp" />
        <set name="weight" value="8" />
        <set name="price" value="5400" />
        <set name="durability" value="48;70" />
        <stats>
            <add stat="attack_damage" value="6;9;11;14" />
            <add stat="attack_speed" value="7" />
            <add stat="attack_rating" value="45;52" />
            <add stat="critical_rate" value="5;" />
        </stats>
        <req>
            <base stat="level" value="17" />
            <base stat="strength" value="62" />
            <base stat="agility" value="40" />
        </req>
    </item>
    <item id="WS208" type="Weapon" name="Templar Sword">
        <set name="weapon_type" value="Sword" />
        <set name="body_part" value="lhand" />
        <set name="default_action" value="EQUIP" />
        <set name="image" value="sinimages\items\weapons\Sword\itWS208.bmp" />
        <set name="weight" value="8" />
        <set name="price" value="9300" />
        <set name="durability" value="45;65" />
        <stats>
            <add stat="attack_damage" value="7;9;13;15" />
            <add stat="attack_speed" value="7" />
            <add stat="attack_rating" value="42;46" />
            <add stat="critical_rate" value="6" />
        </stats>
        <req>
            <base stat="level" value="24" />
            <base stat="strength" value="40" />
            <base stat="spirit" value="30" />
            <base stat="talent" value="40" />
        </req>
    </item>
    <item id="WS209" type="Weapon" name="Shield Sword">
        <set name="weapon_type" value="Sword" />
        <set name="body_part" value="lhand" />
        <set name="default_action" value="EQUIP" />
        <set name="image" value="sinimages\items\weapons\Sword\itWS209.bmp" />
        <set name="weight" value="9" />
        <set name="price" value="13000" />
        <set name="durability" value="50;75" />
        <stats>
            <add stat="attack_damage" value="8;12;16;18" />
            <add stat="attack_speed" value="7" />
            <add stat="attack_rating" value="45;56" />
            <add stat="critical_rate" value="7" />
        </stats>
        <req>
            <base stat="level" value="30" />
            <base stat="strength" value="66" />
            <base stat="talent" value="52" />
            <base stat="agility" value="40" />
        </req>
    </item>
    <item id="WS210" type="Weapon" name="Plated Sword">
        <set name="weapon_type" value="Sword" />
        <set name="body_part" value="lhand" />
        <set name="default_action" value="EQUIP" />
        <set name="image" value="sinimages\items\weapons\Sword\itWS210.bmp" />
        <set name="weight" value="13" />
        <set name="price" value="16000" />
        <set name="durability" value="60;80" />
        <stats>
            <add stat="attack_damage" value="13;16;21;25" />
            <add stat="attack_speed" value="7" />
            <add stat="attack_rating" value="50;62" />
            <add stat="critical_rate" value="12" />
            <add stat="block_rating" value="7;7" />
        </stats>
        <req>
            <base stat="level" value="37" />
            <base stat="strength" value="76" />
            <base stat="talent" value="82" />
        </req>
    </item>
